### ISSUE TITLE
[Bug]: Tool models aren't rendered correctly 

### ISSUE THREAD

**Issue by Gotkoew** [terrarium-earth/Experience-Obelisk#18]
### Bug Description

Tools in 3rd person are rendered as items. 
I believe it it caused by the item model .json, where the mod uses `"parent": "item/generated"`  _(used to render regular items)_  instead of `"parent": "minecraft:item/handheld"` _(used to render tools)_

### How to Reproduce?

1. Put any tool into your hand
2. Look at your character and the tool its holding from 3rd person

### Version

2.0.0

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by cyanog3n** [comment]
Thank you for the report!
