### ISSUE TITLE
Duping experience

### ISSUE THREAD

**Issue by 4u4aaa** [terrarium-earth/Experience-Obelisk#19]
### Bug Description

Duping experience through the experience obelisk. If you break and put the obelisk through the installer and block destroyer from Industrial Foregoing, then at the time of installation you can take experience from the obelisk

### How to Reproduce?

https://www.youtube.com/watch?v=VH11EG7W05Y

### Version

1.4.8

### Mod Loader Version

1.20.1 47.2.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by cyanog3n** [comment]
Hi, version 1.4.8 is no longer supported. From my testing, duplicating XP is no longer possible with this setup as of v2.0.3. If you are playing a modpack, please contact the modpack author and ask them to update the mod file accordingly. Thank you for the report!
